# Generated by Django 3.1.4 on 2020-12-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinit_profile', '0004_auto_20201121_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='none', max_length=255)),
                ('description', models.CharField(default='', max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='pinit_profile.profile')),
            ],
            options={
                'ordering': ['created', 'likes'],
            },
        ),
    ]
