# Generated by Django 3.1.4 on 2020-12-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinit_profile', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Title', max_length=255),
        ),
    ]
