
// USER ACTIONS
export const SET_USER = 'SET_USER';
export const REMOVE_USER = 'REMOVE_USER';

// REGISTER ACTIONS
const UPDATE_USERNAME = 'UPDATE_USERNAME';
const UPDATE_EMAIL = 'UPDATE_EMAIL';
const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
const UPDATE_PASSWORD2 = 'UPDATE_PASSWORD2';
